mkdir -p intermediates
mkdir -p build

rm -r intermediates/*
rm -r build/*

# make country info
## web
echo "var countries=[" > intermediates/countries_web.js
COUNTRY_SQL="select '\"' || country || '\",' from country"
sqlite3 cities.db "$COUNTRY_SQL" >> intermediates/countries_web.js
echo "];" >> intermediates/countries_web.js

## iOS
cp intermediates/countries_web.js intermediates/countries_ios.ts
echo "export default countries;" >> intermediates/countries_ios.ts


# make admin1 info
## web
echo "var admin1=[" > intermediates/admin1_web.js
ADMIN1_SQL="select '\"' || asciiname || '\",' from admin1"
sqlite3 cities.db "$ADMIN1_SQL" >> intermediates/admin1_web.js
echo "];" >> intermediates/admin1_web.js

## iOS
cp intermediates/admin1_web.js intermediates/admin1_ios.ts
echo "export default admin1;" >> intermediates/admin1_ios.ts


# make city info
## web
INFO_SQL="select c.geonameid, printf('%d', 10 * c.latitude), printf('%d', 10 * c.longitude), (a.rowid-1) as countryId, (ad.rowid-1) as admin1 from geoname c left outer join country a on a.iso = c.country left outer join admin1 ad on ad.key = c.country || '.' || c.admin1"
sqlite3 cities.db "$INFO_SQL" > intermediates/info.csv
python compress.py intermediates/info.csv intermediates/info_web.js

## iOS
python compress.py intermediates/info.csv intermediates/info_ios.ts false
echo "export default cityInfo;" >> intermediates/info_ios.ts


# make city names
## web
echo "var cities=[" > intermediates/cities_web.js
CITIES_SQL_WEB="select '[\"' || c.asciiname || '\",' || printf('%d', 10*log(c.population)) || '],' from geoname c"
sqlite3 cities.db "$CITIES_SQL_WEB" >> intermediates/cities_web.js
echo "];" >> intermediates/cities_web.js

## iOS
echo "var cities=[" > intermediates/cities_ios.ts
CITIES_SQL_iOS="select '[\"' || c.asciiname || '\",' || (c.rowid-1) || '],' from geoname c order by population desc"
sqlite3 cities.db "$CITIES_SQL_iOS" >> intermediates/cities_ios.ts
echo "]; export default cities;" >> intermediates/cities_ios.ts



## android
CITY_NAMES_SQL_ANDROID="SELECT '\"' || asciiname || '\",' from geoname ORDER BY population DESC"
CITY_OFFSETS_SQL_ANDROID="SELECT (rowid-1) || ',' from geoname ORDER BY population DESC"
INFO_SQL_ANDROID="select c.geonameid, printf('%d', 10*c.latitude), printf('%d', 10*c.longitude), (a.rowid-1) as countryId, (ad.rowid-1) as admin1, '' from geoname c left outer join country a on a.iso = c.country left outer join admin1 ad on ad.key = c.country || '.' || c.admin1"

CITY_COUNT=$(sqlite3 cities.db "SELECT count(*) from geoname")
PAGE_SIZE=1000

N=$((($CITY_COUNT+$PAGE_SIZE-1)/$PAGE_SIZE))
echo "Making $N pages"

ANDROID_DATA_PATH="build/android"
ANDROID_RAW_DATA_PATH="$ANDROID_DATA_PATH/raw"

mkdir -p "$ANDROID_RAW_DATA_PATH"

allCitiesFile="$ANDROID_DATA_PATH/CitiesDB.java"

echo -e "package com.findstarlink.data;\n" > "$allCitiesFile"
echo -e "// AUTOGENERATED. DO NOT MODIFY\n" >> "$allCitiesFile"
echo -e "import com.findstarlink.data.raw.*;\n\npublic class CitiesDB {" >> "$allCitiesFile"

echo -e "  public static int infoFieldCount = 5;" >> "$allCitiesFile"
echo -e "  public static int pageSize = $PAGE_SIZE;\n" >> "$allCitiesFile"

citiesList=""
cityOffsetsList=""
infoList=""

for i in $(seq 0 $(($N-1))); do
	OFFSET=$(($i * $PAGE_SIZE))

	# cities part
	citiesFile="$ANDROID_RAW_DATA_PATH/Cities$i.java"

	echo -e "package com.findstarlink.data.raw;\n\npublic class Cities$i {" > "$citiesFile"

	echo -e "public static String[] data = new String[] {" >> "$citiesFile"
	sqlite3 cities.db "$CITY_NAMES_SQL_ANDROID LIMIT $PAGE_SIZE OFFSET $OFFSET" >> "$citiesFile"
	echo -e "};\n" >> "$citiesFile"

	echo -e "public static int[] offsets = new int[] {" >> "$citiesFile"
	sqlite3 cities.db "$CITY_OFFSETS_SQL_ANDROID LIMIT $PAGE_SIZE OFFSET $OFFSET" >> "$citiesFile"
	echo -e "};" >> "$citiesFile"

	echo -e "}" >> "$citiesFile"

	citiesList=$citiesList"\n    Cities$i.data,"
	citiesOffsetsList=$citiesOffsetsList"\n    Cities$i.offsets,"

	# info part
	infoFile="$ANDROID_RAW_DATA_PATH/Info$i.java"

	echo -e "package com.findstarlink.data.raw;\n\npublic class Info$i {\npublic static int[] data = new int[] {" > "$infoFile"
	sqlite3 cities.db ".separator ','" ".nullvalue '-1'" "$INFO_SQL_ANDROID LIMIT $PAGE_SIZE OFFSET $OFFSET" >> "$infoFile"
	echo -e "};\n}" >> "$infoFile"

	infoList=$infoList"\n    Info$i.data,"
done

echo -e "  static String[][] citiesPages = new String[][]{$citiesList\n  };\n" >> "$allCitiesFile"
echo -e "  static int[][] citiesOffsets = new int[][]{$citiesOffsetsList\n  };\n" >> "$allCitiesFile"
echo -e "  static int[][] infoPages = new int[][]{$infoList\n  };\n" >> "$allCitiesFile"
echo -e "  public static String[] countries = Countries.data;\n" >> "$allCitiesFile"
echo -e "  public static String[] admin1 = Admin1.data;" >> "$allCitiesFile"

echo -e "}" >> "$allCitiesFile"

# countries
COUNTRY_SQL_ANDROID="select '\"' || country || '\",' from country"
countriesFile="$ANDROID_RAW_DATA_PATH/Countries.java"

echo -e "package com.findstarlink.data.raw;\n\npublic class Countries {\npublic static String[] data = new String[] {" > "$countriesFile"
sqlite3 cities.db "$COUNTRY_SQL_ANDROID" >> "$countriesFile"
echo -e "};\n}" >> "$countriesFile"

# admin1
ADMIN1_SQL_ANDROID="select '\"' || asciiname || '\",' from admin1"
admin1File="$ANDROID_RAW_DATA_PATH/Admin1.java"

echo -e "package com.findstarlink.data.raw;\n\npublic class Admin1 {\npublic static String[] data = new String[] {" > "$admin1File"
sqlite3 cities.db "$ADMIN1_SQL_ANDROID" >> "$admin1File"
echo -e "};\n}" >> "$admin1File"



# merge
## web
cat intermediates/countries_web.js intermediates/admin1_web.js intermediates/cities_web.js intermediates/info_web.js > build/cities_web.js
zip build/cities_web.zip build/cities_web.js

## iOS
cp intermediates/countries_ios.ts intermediates/admin1_ios.ts intermediates/cities_ios.ts intermediates/info_ios.ts build/


# list
ls -ltrh build/