# Generated initially using github-actions-wizard (https://github.com/cmdr2/github-actions-wizard)

name: CI Pipeline
run-name: CI Pipeline
on:
  release:
    types:
    - created
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.x'
    - name: Fetch cities data
      run: |-
        sh import-db.sh
    - name: Build the bundle
      run: |-
        sh make-bundle.sh
        mv build build-temp
    - name: Zip individual build targets
      run: |-
        mkdir build
        cd build-temp
        zip -r ../build/web.zip cities_web.js
        zip -r ../build/typescript.zip countries_ios.ts admin1_ios.ts cities_ios.ts info_ios.ts
        zip -r ../build/android.zip android
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: build
  deploy_to_gh_release_on_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    if: github.event_name == 'release' && github.event.action == 'created'
    needs: build
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v5
      with:
        name: build
        path: .
    - name: Release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        files: |-
          web.zip
          typescript.zip
          android.zip
